# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '37 2 * * *'
  
  workflow_dispatch:  # This allows manual triggering

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install -e .
        pwd
        ls -la

    - name: Download cache files
      run: |
        curl -O ${{ secrets.CACHE_FILE_URL }}
        curl -O ${{ secrets.CONFIG_FILE_URL }}
        curl -O ${{ secrets.SESSION_FILE_URL }}
        ls -la
      env:
        CACHE_FILE_URL: ${{ secrets.CACHE_FILE_URL }}
        CONFIG_FILE_URL: ${{ secrets.CONFIG_FILE_URL }}
        SESSION_FILE_URL: ${{ secrets.SESSION_FILE_URL }}


    - name: Sync Spotify playlists
      run: |
        spotify_to_tidal --uri 0Sb5d3YXIGSKyvNSt15hb6
